# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_location', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager_start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_to_depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='management.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='depart_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department'),
        ),
        migrations.AddField(
            model_name='project',
            name='employee_on_project',
            field=models.ManyToManyField(to='management.Employee'),
        ),
        migrations.AddField(
            model_name='departmentlocation',
            name='depart_object_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentlocation',
            unique_together=set([('depart_object_ref', 'depart_location')]),
        ),
    ]
